package com.spark.mybatis.model;

import java.util.Date;

public class TbLogs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_logs.id
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_logs.time
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_logs.persion
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    private String persion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_logs.logInfo
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    private String loginfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_logs.id
     *
     * @return the value of tb_logs.id
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_logs.id
     *
     * @param id the value for tb_logs.id
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_logs.time
     *
     * @return the value of tb_logs.time
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_logs.time
     *
     * @param time the value for tb_logs.time
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_logs.persion
     *
     * @return the value of tb_logs.persion
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    public String getPersion() {
        return persion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_logs.persion
     *
     * @param persion the value for tb_logs.persion
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    public void setPersion(String persion) {
        this.persion = persion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_logs.logInfo
     *
     * @return the value of tb_logs.logInfo
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    public String getLoginfo() {
        return loginfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_logs.logInfo
     *
     * @param loginfo the value for tb_logs.logInfo
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    public void setLoginfo(String loginfo) {
        this.loginfo = loginfo;
    }
}