package com.spark.mybatis.mapper;

import com.spark.mybatis.model.TbLogs;
import java.util.List;

public interface TbLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_logs
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_logs
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    int insert(TbLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_logs
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    TbLogs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_logs
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    List<TbLogs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_logs
     *
     * @mbg.generated Fri Apr 24 11:31:17 CST 2020
     */
    int updateByPrimaryKey(TbLogs record);
}